---

_vendor:   curvytron
_app:      blend
_app_dir:  /srv/app
_app_host: "{{ _app ~ ('.' ~ _vendor if _vendor else '') }}"
_env:  dev

########
# Motd #
########

elao_motd_template: template/empty.j2
elao_motd:          Curvytron - Blend Edition

############
# Timezone #
############

elao_timezone: Etc/UTC

#######
# Apt #
#######

elao_apt_update: true

elao_apt_repositories:
  - bearstech
  - backports
  - nginx
  - nodesource_4
  - grafana

elao_apt_preferences:
  - git@backports
  - nginx@nginx
  - nodejs@nodesource_4
  - grafana@grafana

elao_apt_packages:
  - name: g++

#######
# Ssh #
#######

elao_ssh_config_sshd_template: config/sshd/{{ _env }}.j2

elao_ssh_config_template: config/{{ _env }}.j2
elao_ssh_config: []

#######
# Git #
#######

elao_git_config_template: config/{{ _env }}.j2

#############
# Oh my zsh #
#############

elao_ohmyzsh_users:
  - user:     "{{ _user }}"
    template: users/{{ _env }}.j2
    config:
      - |
        elao_php_xdebug () {
            if [[ $1 == on ]]; then sudo mv /etc/php5/fpm/conf.d/20-xdebug.ini.off /etc/php5/fpm/conf.d/20-xdebug.ini
            else sudo mv /etc/php5/fpm/conf.d/20-xdebug.ini /etc/php5/fpm/conf.d/20-xdebug.ini.off; fi
            sudo service php5-fpm restart
        }
      - cd {{ _app_dir }}

#######
# Gem #
#######

#elao_gem_packages: []

##########
# Log.io #
##########

elao_logio_config_harvester:
  - nodeName: App
  - logStreams:
    - nginx:
      - "{{ elao_nginx_log_dir }}/app.access.log"
      - "{{ elao_nginx_log_dir }}/app.error.log"
    - nodejs:
      - "{{ elao_supervisor_log_dir }}/server.log"

#########
# Nginx #
#########

elao_nginx_config_template: config/http_{{ _env }}.conf.j2

elao_nginx_configs_exclusive: true
_nginx_configs:
  # Gzip
  - file:     gzip
    template: configs/gzip_{{ _env }}.j2
  # Default 404
  - file:     00-default.conf
    template: configs/server_{{ _env }}.conf.j2
    config:
      - return: 404
  # App static
  - file:     "{{ _app_host }}.conf"
    template: configs/server_{{ _env }}.conf.j2
    config:
      - server_name: "{{ _app_host }}.dev"
      - root:       "{{ _app_dir }}/web"
      #- listen:     "{{ ansible_eth1.ipv4.address }}:80"
      - access_log: "{{ elao_nginx_log_dir }}/app.access.log"
      - error_log:  "{{ elao_nginx_log_dir }}/app.error.log"
      - include:     conf.d/gzip
      - charset:    "UTF-8"

#######
# Npm #
#######

elao_npm_packages:
  - { name: bower, version: 1 }
  - { name: gulp, version: 3 }
  - { name: usage, version: 0 }
  - { name: md5, version: 2 }
  - { name: influx, version: 4 }

##############
# Supervisor #
##############

elao_supervisor_config_template: config/{{ _env }}.conf.j2

elao_supervisor_configs_exclusive: true
elao_supervisor_configs:
  - file:     inet-http-server.conf
    template: configs/inet_http_server_{{ _env }}.conf.j2
  - file:     server.conf
    template: configs/program_{{ _env }}.conf.j2
    config:
      - server:
        - command:         node bin/curvytron.js
        - directory:       "{{ _app_dir }}"
        - user:            "vagrant"
        - autorestart:     true
        - stdout_logfile:  "{{ elao_supervisor_log_dir }}/server.log"
        - redirect_stderr: true
