---

_vendor:   curvytron
_app:      blend
_app_dir:  /srv/app
_app_host: "{{ _app ~ ('.' ~ _vendor if _vendor else '') }}"
_env:      dev

########
# Motd #
########

elao_motd_template: template/empty.j2
elao_motd:          Curvytron - Blend Edition

############
# Timezone #
############

elao_timezone: Etc/UTC

#######
# Apt #
#######

elao_apt_update: true

elao_apt_repositories:
  - bearstech
  - backports
  - nginx
  - nodesource_4
  - grafana

elao_apt_preferences:
  - git@backports
  - nginx@nginx
  - nodejs@nodesource_4
  - grafana@grafana

elao_apt_packages:
  - name: g++

#######
# Ssh #
#######

elao_ssh_config_sshd_template: config/sshd/{{ _env }}.j2

elao_ssh_config_template: config/{{ _env }}.j2
elao_ssh_config: []

#######
# Git #
#######

elao_git_config_template: config/{{ _env }}.j2

#############
# Oh my zsh #
#############

elao_ohmyzsh_users:
  - user:     "{{ _user }}"
    template: users/{{ _env }}.j2
    config:
      - ZSH_THEME: elao-dev
      - plugins: (git debian common-aliases history history-substring-search npm bower)
      - cd {{ _app_dir }}

##########
# Log.io #
##########

elao_logio_config_harvester:
  - nodeName: App
  - logStreams:
    - nginx:
      - "{{ elao_nginx_log_dir }}/app.access.log"
      - "{{ elao_nginx_log_dir }}/app.error.log"
    - nodejs:
      - "{{ elao_supervisor_log_dir }}/server.log"

#########
# Nginx #
#########

elao_nginx_config_template: config/http_{{ _env }}.conf.j2

elao_nginx_configs_exclusive: true
elao_nginx_configs:
  # Gzip
  - file:     gzip
    template: configs/gzip_{{ _env }}.j2
  # Game
  - file:     "{{ _app_host }}.conf"
    template: configs/server_{{ _env }}.conf.j2
    config:
      - server_name: "{{ _app_host }}.dev"
      - root:        "{{ _app_dir }}/web"
      #- listen:      "{{ ansible_eth1.ipv4.address }}:80"
      - access_log:  "{{ elao_nginx_log_dir }}/app.access.log"
      - error_log:   "{{ elao_nginx_log_dir }}/app.error.log"
      - include:     conf.d/gzip
      - charset:     "UTF-8"
      - location /:
        - proxy_pass:         "http://127.0.0.1:8080"
        - proxy_http_version: "1.1"
        - proxy_set_header:   "Upgrade $http_upgrade"
        - proxy_set_header:   'Connection "upgrade"'
        - proxy_set_header:   "Host $host"
        - proxy_set_header:   "X-Real-IP $remote_addr"
        - proxy_set_header:   "X-Forwarded-For $proxy_add_x_forwarded_for"

############
# InfluxDB #
############

elao_influxdb_databases:
  - curvytron

elao_influxdb_users:
 - { database: curvytron, name: curvytron, password: curvytron }

elao_influxdb_privileges:
 - { database: curvytron, user: curvytron, grant: ALL }

#######
# Npm #
#######

elao_npm_packages:
  - { name: bower, version: 1 }
  - { name: gulp, version: 3 }
  - { name: usage, version: 0 }
  - { name: md5, version: 2 }
  - { name: influx, version: 4 }

##############
# Supervisor #
##############

elao_supervisor_config_template: config/{{ _env }}.conf.j2

elao_supervisor_configs_exclusive: true
elao_supervisor_configs:
  - file:     inet-http-server.conf
    template: configs/inet_http_server_{{ _env }}.conf.j2
  - file:     server.conf
    template: configs/program_{{ _env }}.conf.j2
    config:
      - server:
        - command:         node bin/curvytron.js
        - directory:       "{{ _app_dir }}"
        - user:            "vagrant"
        - autorestart:     true
        - stdout_logfile:  "{{ elao_supervisor_log_dir }}/server.log"
        - redirect_stderr: true
